-- Seed Exercises para GymTracker PWA (100 ejercicios)

INSERT INTO exercises (name, muscle_group, submuscles, equipment, description, difficulty, image_url, is_home, is_gym, created_at) VALUES

-- PIERNAS (1-20)
('Sentadilla con barra', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Barra', 'Sentadilla profunda controlada', 'Intermedio', '/images/exercises/sentadilla-barra.jpg', false, true, NOW()),
('Sentadilla goblet', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Mancuerna', 'Sentadilla sosteniendo mancuerna', 'Principiante', '/images/exercises/goblet-squat.jpg', true, true, NOW()),
('Hack squat', 'Piernas', ARRAY['Cuádriceps'], 'Máquina', 'Sentadilla guiada inclinada', 'Intermedio', '/images/exercises/hack-squat.jpg', false, true, NOW()),
('Prensa inclinada', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Máquina', 'Empuje de piernas en plataforma', 'Principiante', '/images/exercises/leg-press.jpg', false, true, NOW()),
('Peso muerto rumano', 'Piernas', ARRAY['Isquiotibiales', 'Glúteos'], 'Barra', 'Bisagra de cadera controlada', 'Intermedio', '/images/exercises/rdl.jpg', true, true, NOW()),
('Peso muerto convencional', 'Espalda', ARRAY['Espalda baja', 'Glúteos'], 'Barra', 'Levantamiento desde el suelo', 'Avanzado', '/images/exercises/deadlift.jpg', false, true, NOW()),
('Curl femoral acostado', 'Piernas', ARRAY['Isquiotibiales'], 'Máquina', 'Flexión de rodillas acostado', 'Principiante', '/images/exercises/leg-curl.jpg', false, true, NOW()),
('Curl femoral sentado', 'Piernas', ARRAY['Isquiotibiales'], 'Máquina', 'Flexión sentado en máquina', 'Principiante', '/images/exercises/seated-leg-curl.jpg', false, true, NOW()),
('Extensión de cuádriceps', 'Piernas', ARRAY['Cuádriceps'], 'Máquina', 'Extensión de rodillas sentado', 'Principiante', '/images/exercises/leg-extension.jpg', false, true, NOW()),
('Hip thrust', 'Piernas', ARRAY['Glúteos'], 'Barra', 'Empuje de cadera elevado', 'Intermedio', '/images/exercises/hip-thrust.jpg', true, true, NOW()),
('Sentadilla búlgara', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Mancuernas', 'Sentadilla unilateral elevada', 'Intermedio', '/images/exercises/bulgarian-squat.jpg', true, true, NOW()),
('Zancadas caminando', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Mancuernas', 'Pasos largos con carga', 'Intermedio', '/images/exercises/walking-lunges.jpg', true, true, NOW()),
('Step up', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Mancuernas', 'Subida a banco controlada', 'Principiante', '/images/exercises/step-up.jpg', true, true, NOW()),
('Elevación de gemelos de pie', 'Piernas', ARRAY['Pantorrillas'], 'Máquina', 'Elevación de talones de pie', 'Principiante', '/images/exercises/calf-raise.jpg', false, true, NOW()),
('Elevación de gemelos sentado', 'Piernas', ARRAY['Pantorrillas'], 'Máquina', 'Elevación sentado con carga', 'Principiante', '/images/exercises/seated-calf-raise.jpg', false, true, NOW()),
('Aductores en máquina', 'Piernas', ARRAY['Aductores'], 'Máquina', 'Cierre de piernas controlado', 'Principiante', '/images/exercises/adductors.jpg', false, true, NOW()),
('Abductores en máquina', 'Piernas', ARRAY['Abductores'], 'Máquina', 'Apertura de piernas controlada', 'Principiante', '/images/exercises/abductors.jpg', false, true, NOW()),
('Pistol squat asistida', 'Piernas', ARRAY['Cuádriceps', 'Core'], 'Peso corporal', 'Sentadilla unilateral asistida', 'Avanzado', '/images/exercises/pistol-squat.jpg', true, true, NOW()),
('Puente de glúteo', 'Piernas', ARRAY['Glúteos'], 'Peso corporal', 'Elevación de cadera en suelo', 'Principiante', '/images/exercises/glute-bridge.jpg', true, true, NOW()),
('Saltos al cajón', 'Piernas', ARRAY['Cuádriceps', 'Glúteos'], 'Caja', 'Salto explosivo al cajón', 'Intermedio', '/images/exercises/box-jump.jpg', true, true, NOW()),

-- PECHO (21-35)
('Press banca plano', 'Pecho', ARRAY['Pecho medio', 'Tríceps'], 'Barra', 'Empuje horizontal clásico', 'Intermedio', '/images/exercises/bench-press.jpg', false, true, NOW()),
('Press inclinado con barra', 'Pecho', ARRAY['Pecho superior'], 'Barra', 'Press en banco inclinado', 'Intermedio', '/images/exercises/incline-bench.jpg', false, true, NOW()),
('Press inclinado con mancuernas', 'Pecho', ARRAY['Pecho superior'], 'Mancuernas', 'Press inclinado unilateral', 'Intermedio', '/images/exercises/incline-db-press.jpg', true, true, NOW()),
('Press pecho en máquina', 'Pecho', ARRAY['Pecho medio'], 'Máquina', 'Empuje guiado en máquina', 'Principiante', '/images/exercises/chest-press.jpg', false, true, NOW()),
('Fondos en paralelas', 'Pecho', ARRAY['Pecho inferior', 'Tríceps'], 'Peso corporal', 'Descenso entre barras', 'Intermedio', '/images/exercises/dips.jpg', true, true, NOW()),
('Fondos en máquina', 'Pecho', ARRAY['Pecho inferior'], 'Máquina', 'Fondos asistidos guiados', 'Principiante', '/images/exercises/assisted-dips.jpg', false, true, NOW()),
('Flexiones tradicionales', 'Pecho', ARRAY['Pecho medio'], 'Peso corporal', 'Empuje corporal en suelo', 'Principiante', '/images/exercises/pushups.jpg', true, true, NOW()),
('Flexiones diamante', 'Brazos', ARRAY['Tríceps', 'Pecho interno'], 'Peso corporal', 'Flexión con manos cerradas', 'Intermedio', '/images/exercises/diamond-pushups.jpg', true, true, NOW()),
('Flexiones inclinadas', 'Pecho', ARRAY['Pecho inferior'], 'Peso corporal', 'Flexión apoyado en banco', 'Principiante', '/images/exercises/incline-pushups.jpg', true, true, NOW()),
('Flexiones declinadas', 'Pecho', ARRAY['Pecho superior'], 'Peso corporal', 'Flexión con pies elevados', 'Intermedio', '/images/exercises/decline-pushups.jpg', true, true, NOW()),
('Aperturas con mancuernas', 'Pecho', ARRAY['Pecho medio'], 'Mancuernas', 'Apertura controlada en banco', 'Intermedio', '/images/exercises/db-flyes.jpg', true, true, NOW()),
('Aperturas en cable', 'Pecho', ARRAY['Pecho medio'], 'Cable', 'Cruce de poleas controlado', 'Intermedio', '/images/exercises/cable-flyes.jpg', false, true, NOW()),
('Chest press cable', 'Pecho', ARRAY['Pecho medio'], 'Cable', 'Empuje frontal en polea', 'Principiante', '/images/exercises/cable-press.jpg', false, true, NOW()),
('Pullover con mancuerna', 'Espalda', ARRAY['Dorsales', 'Pecho'], 'Mancuerna', 'Apertura sobre cabeza', 'Intermedio', '/images/exercises/db-pullover.jpg', true, true, NOW()),
('Pullover en polea', 'Espalda', ARRAY['Dorsales'], 'Cable', 'Jalón extendido al torso', 'Intermedio', '/images/exercises/cable-pullover.jpg', false, true, NOW()),

-- ESPALDA (36-50)
('Dominadas', 'Espalda', ARRAY['Dorsales', 'Bíceps'], 'Peso corporal', 'Jalón corporal en barra', 'Avanzado', '/images/exercises/pullups.jpg', true, true, NOW()),
('Dominadas asistidas', 'Espalda', ARRAY['Dorsales'], 'Máquina', 'Dominada con asistencia', 'Intermedio', '/images/exercises/assisted-pullups.jpg', false, true, NOW()),
('Jalón al pecho', 'Espalda', ARRAY['Dorsales'], 'Cable', 'Jalón vertical controlado', 'Principiante', '/images/exercises/lat-pulldown.jpg', false, true, NOW()),
('Jalón agarre neutro', 'Espalda', ARRAY['Dorsales', 'Romboides'], 'Cable', 'Jalón con agarre cerrado', 'Principiante', '/images/exercises/neutral-grip-pulldown.jpg', false, true, NOW()),
('Remo con barra', 'Espalda', ARRAY['Dorsales', 'Romboides'], 'Barra', 'Remo inclinado pesado', 'Intermedio', '/images/exercises/barbell-row.jpg', false, true, NOW()),
('Remo sentado en polea', 'Espalda', ARRAY['Dorsales', 'Trapecio'], 'Cable', 'Remo horizontal sentado', 'Principiante', '/images/exercises/seated-row.jpg', false, true, NOW()),
('Remo unilateral mancuerna', 'Espalda', ARRAY['Dorsales'], 'Mancuerna', 'Remo a una mano', 'Principiante', '/images/exercises/db-row.jpg', true, true, NOW()),
('Remo T-Bar', 'Espalda', ARRAY['Trapecio', 'Dorsales'], 'Máquina', 'Remo en barra T', 'Intermedio', '/images/exercises/tbar-row.jpg', false, true, NOW()),
('Remo invertido', 'Espalda', ARRAY['Dorsales', 'Bíceps'], 'Peso corporal', 'Remo suspendido corporal', 'Intermedio', '/images/exercises/inverted-row.jpg', true, true, NOW()),
('Face pull', 'Hombros', ARRAY['Deltoide posterior'], 'Cable', 'Jalón hacia la cara', 'Principiante', '/images/exercises/face-pull.jpg', false, true, NOW()),
('Encogimientos con barra', 'Espalda', ARRAY['Trapecio'], 'Barra', 'Elevación de hombros', 'Principiante', '/images/exercises/barbell-shrugs.jpg', false, true, NOW()),
('Encogimientos con mancuernas', 'Espalda', ARRAY['Trapecio'], 'Mancuernas', 'Elevación lateral de hombros', 'Principiante', '/images/exercises/db-shrugs.jpg', true, true, NOW()),
('Superman', 'Core', ARRAY['Lumbar'], 'Peso corporal', 'Extensión lumbar en suelo', 'Principiante', '/images/exercises/superman.jpg', true, true, NOW()),
('Buenos días', 'Espalda', ARRAY['Espalda baja', 'Glúteos'], 'Barra', 'Flexión de torso controlada', 'Intermedio', '/images/exercises/good-morning.jpg', false, true, NOW()),
('Peso muerto sumo', 'Piernas', ARRAY['Glúteos', 'Aductores'], 'Barra', 'Peso muerto con postura amplia', 'Intermedio', '/images/exercises/sumo-deadlift.jpg', false, true, NOW()),

-- HOMBROS (51-60)
('Press militar', 'Hombros', ARRAY['Deltoide anterior'], 'Barra', 'Empuje vertical de hombros', 'Intermedio', '/images/exercises/military-press.jpg', false, true, NOW()),
('Press militar sentado', 'Hombros', ARRAY['Deltoide anterior'], 'Mancuernas', 'Press sentado controlado', 'Principiante', '/images/exercises/seated-press.jpg', true, true, NOW()),
('Press Arnold', 'Hombros', ARRAY['Deltoides completos'], 'Mancuernas', 'Rotación y press de hombros', 'Intermedio', '/images/exercises/arnold-press.jpg', true, true, NOW()),
('Elevaciones laterales', 'Hombros', ARRAY['Deltoide lateral'], 'Mancuernas', 'Elevación lateral controlada', 'Principiante', '/images/exercises/lateral-raise.jpg', true, true, NOW()),
('Elevaciones laterales en polea', 'Hombros', ARRAY['Deltoide lateral'], 'Cable', 'Elevación unilateral en polea', 'Intermedio', '/images/exercises/cable-lateral-raise.jpg', false, true, NOW()),
('Pájaros con mancuernas', 'Hombros', ARRAY['Deltoide posterior'], 'Mancuernas', 'Apertura inclinada posterior', 'Principiante', '/images/exercises/db-flye-rear.jpg', true, true, NOW()),
('Reverse fly en máquina', 'Hombros', ARRAY['Deltoide posterior'], 'Máquina', 'Apertura posterior guiada', 'Principiante', '/images/exercises/reverse-flye.jpg', false, true, NOW()),
('Pike push up', 'Hombros', ARRAY['Deltoide anterior'], 'Peso corporal', 'Flexión vertical corporal', 'Intermedio', '/images/exercises/pike-pushup.jpg', true, true, NOW()),
('Handstand push up asistida', 'Hombros', ARRAY['Hombros', 'Tríceps'], 'Peso corporal', 'Flexión invertida asistida', 'Avanzado', '/images/exercises/handstand-pushup.jpg', true, true, NOW()),
('Elevaciones frontales', 'Hombros', ARRAY['Deltoide anterior'], 'Mancuernas', 'Elevación frontal controlada', 'Principiante', '/images/exercises/front-raise.jpg', true, true, NOW()),

-- BRAZOS (61-78)
('Curl bíceps con barra', 'Brazos', ARRAY['Bíceps'], 'Barra', 'Curl clásico de pie', 'Principiante', '/images/exercises/barbell-curl.jpg', false, true, NOW()),
('Curl bíceps barra EZ', 'Brazos', ARRAY['Bíceps'], 'Barra EZ', 'Curl con agarre cómodo', 'Principiante', '/images/exercises/ez-curl.jpg', false, true, NOW()),
('Curl alterno', 'Brazos', ARRAY['Bíceps'], 'Mancuernas', 'Curl alternando brazos', 'Principiante', '/images/exercises/db-curl.jpg', true, true, NOW()),
('Curl martillo', 'Brazos', ARRAY['Bíceps', 'Antebrazo'], 'Mancuernas', 'Curl con agarre neutro', 'Principiante', '/images/exercises/hammer-curl.jpg', true, true, NOW()),
('Curl concentrado', 'Brazos', ARRAY['Bíceps'], 'Mancuerna', 'Curl apoyado unilateral', 'Intermedio', '/images/exercises/concentration-curl.jpg', true, true, NOW()),
('Curl predicador', 'Brazos', ARRAY['Bíceps'], 'Máquina', 'Curl apoyado en banco', 'Principiante', '/images/exercises/preacher-curl.jpg', false, true, NOW()),
('Curl en polea', 'Brazos', ARRAY['Bíceps'], 'Cable', 'Curl continuo en polea', 'Principiante', '/images/exercises/cable-curl.jpg', false, true, NOW()),
('Curl inverso', 'Brazos', ARRAY['Antebrazos'], 'Barra', 'Curl con agarre prono', 'Intermedio', '/images/exercises/reverse-curl.jpg', true, true, NOW()),
('Wrist curl', 'Brazos', ARRAY['Antebrazos'], 'Barra', 'Flexión de muñecas', 'Principiante', '/images/exercises/wrist-curl.jpg', true, true, NOW()),
('Dominada supina', 'Brazos', ARRAY['Bíceps', 'Dorsales'], 'Peso corporal', 'Dominada agarre supino', 'Intermedio', '/images/exercises/chin-up.jpg', true, true, NOW()),
('Extensión tríceps cuerda', 'Brazos', ARRAY['Tríceps'], 'Cable', 'Extensión con cuerda', 'Principiante', '/images/exercises/rope-extension.jpg', false, true, NOW()),
('Extensión tríceps overhead', 'Brazos', ARRAY['Tríceps'], 'Mancuerna', 'Extensión sobre cabeza', 'Principiante', '/images/exercises/overhead-extension.jpg', true, true, NOW()),
('Fondos en banco', 'Brazos', ARRAY['Tríceps'], 'Peso corporal', 'Descenso apoyado en banco', 'Principiante', '/images/exercises/bench-dips.jpg', true, true, NOW()),
('Press francés', 'Brazos', ARRAY['Tríceps'], 'Barra EZ', 'Extensión acostado', 'Intermedio', '/images/exercises/french-press.jpg', true, true, NOW()),
('Patada de tríceps', 'Brazos', ARRAY['Tríceps'], 'Mancuerna', 'Extensión posterior unilateral', 'Principiante', '/images/exercises/kickback.jpg', true, true, NOW()),
('Extensión unilateral cable', 'Brazos', ARRAY['Tríceps'], 'Cable', 'Extensión individual en polea', 'Principiante', '/images/exercises/single-cable-extension.jpg', false, true, NOW()),
('Flexiones cerradas', 'Brazos', ARRAY['Tríceps'], 'Peso corporal', 'Flexión enfocada en tríceps', 'Intermedio', '/images/exercises/close-grip-pushups.jpg', true, true, NOW()),
('Rompecráneos', 'Brazos', ARRAY['Tríceps'], 'Barra EZ', 'Extensión acostado pesada', 'Intermedio', '/images/exercises/skull-crushers.jpg', true, true, NOW()),

-- CORE (79-90)
('Plancha abdominal', 'Core', ARRAY['Core profundo'], 'Peso corporal', 'Mantener cuerpo estable', 'Principiante', '/images/exercises/plank.jpg', true, true, NOW()),
('Crunch abdominal', 'Core', ARRAY['Abdominales'], 'Peso corporal', 'Flexión abdominal básica', 'Principiante', '/images/exercises/crunch.jpg', true, true, NOW()),
('Crunch en polea', 'Core', ARRAY['Abdominales'], 'Cable', 'Flexión con resistencia', 'Principiante', '/images/exercises/cable-crunch.jpg', false, true, NOW()),
('Elevaciones de piernas', 'Core', ARRAY['Abdominales inferiores'], 'Peso corporal', 'Elevación de piernas controlada', 'Intermedio', '/images/exercises/leg-raises.jpg', true, true, NOW()),
('Russian twist', 'Core', ARRAY['Oblicuos'], 'Peso corporal', 'Giro de torso sentado', 'Principiante', '/images/exercises/russian-twist.jpg', true, true, NOW()),
('Mountain climbers', 'Core', ARRAY['Core', 'Cardio'], 'Peso corporal', 'Rodillas rápidas al pecho', 'Principiante', '/images/exercises/mountain-climbers.jpg', true, true, NOW()),
('Hollow hold', 'Core', ARRAY['Core profundo'], 'Peso corporal', 'Posición abdominal estática', 'Intermedio', '/images/exercises/hollow-hold.jpg', true, true, NOW()),
('Bird dog', 'Core', ARRAY['Lumbar', 'Core'], 'Peso corporal', 'Extensión alterna controlada', 'Principiante', '/images/exercises/bird-dog.jpg', true, true, NOW()),
('Side plank', 'Core', ARRAY['Oblicuos'], 'Peso corporal', 'Plancha lateral estática', 'Principiante', '/images/exercises/side-plank.jpg', true, true, NOW()),
('Toques al talón', 'Core', ARRAY['Oblicuos'], 'Peso corporal', 'Flexión lateral abdominal', 'Principiante', '/images/exercises/heel-touches.jpg', true, true, NOW()),
('Cable woodchopper', 'Core', ARRAY['Oblicuos'], 'Cable', 'Giro diagonal en polea', 'Intermedio', '/images/exercises/woodchopper.jpg', false, true, NOW()),
('Ab wheel rollout', 'Core', ARRAY['Core profundo'], 'Rueda abdominal', 'Extensión abdominal avanzada', 'Avanzado', '/images/exercises/ab-wheel.jpg', true, true, NOW()),

-- CARDIO & FULL BODY (91-100)
('Battle ropes', 'Cardio', ARRAY['Hombros', 'Core'], 'Cuerdas', 'Ondas explosivas con cuerdas', 'Intermedio', '/images/exercises/battle-ropes.jpg', false, true, NOW()),
('Burpees', 'Cardio', ARRAY['Cuerpo completo'], 'Peso corporal', 'Salto y flexión continua', 'Intermedio', '/images/exercises/burpees.jpg', true, true, NOW()),
('Jumping jacks', 'Cardio', ARRAY['Cuerpo completo'], 'Peso corporal', 'Saltos coordinados', 'Principiante', '/images/exercises/jumping-jacks.jpg', true, true, NOW()),
('Farmer walk', 'Brazos', ARRAY['Antebrazos', 'Trapecio'], 'Mancuernas', 'Caminata con carga', 'Intermedio', '/images/exercises/farmer-walk.jpg', true, true, NOW()),
('Sprints en cinta', 'Cardio', ARRAY['Piernas'], 'Caminadora', 'Carrera intensa corta', 'Intermedio', '/images/exercises/sprints.jpg', false, true, NOW()),
('Kettlebell swing', 'Piernas', ARRAY['Glúteos', 'Lumbar'], 'Kettlebell', 'Balanceo explosivo', 'Intermedio', '/images/exercises/kettlebell-swing.jpg', true, true, NOW()),
('Thrusters con mancuernas', 'Cuerpo completo', ARRAY['Piernas', 'Hombros'], 'Mancuernas', 'Sentadilla y press combinado', 'Intermedio', '/images/exercises/dumbbell-thrusters.jpg', true, true, NOW()),
('Clean and press', 'Cuerpo completo', ARRAY['Hombros', 'Piernas'], 'Barra', 'Levantamiento y press', 'Avanzado', '/images/exercises/clean-press.jpg', false, true, NOW()),
('Renegade row', 'Espalda', ARRAY['Core', 'Dorsales'], 'Mancuernas', 'Remo en posición de plancha', 'Intermedio', '/images/exercises/renegade-row.jpg', true, true, NOW()),
('Bear crawl', 'Core', ARRAY['Core', 'Hombros'], 'Peso corporal', 'Desplazamiento cuadrúpedo', 'Intermedio', '/images/exercises/bear-crawl.jpg', true, true, NOW());

SELECT COUNT(*) as total_exercises FROM exercises;
